Prepare v0.0.3 release
mineiros-io/terraform-google-billing-budget pull request #8
Opened 2022-02-15 18:49 UTC by soerenmartius

2022-02-15 19:35 UTC, mariux requested changes

2022-02-15 19:35 UTC, mariux commented on CHANGELOG.md
>  [0.0.2]: https://github.com/mineiros-io/terraform-google-billing-budget/releases/tag/v0.0.2
those should show a diff not a tag...

2022-02-16 17:16 UTC, mariux requested changes

2022-02-16 17:16 UTC, mariux commented on CHANGELOG.md
> +[0.0.2]: https://github.com/mineiros-io/terraform-google-billing-budget/releases/tag/v0.0.1...v0.0.2
```suggestion
[0.0.3]: https://github.com/mineiros-io/terraform-google-billing-budget/compare/v0.0.2...v0.0.3
[0.0.2]: https://github.com/mineiros-io/terraform-google-billing-budget/compare/v0.0.1...v0.0.2
```

2022-02-16 21:40 UTC, kassianh approved these changes
lgtm

2022-02-16 22:39 UTC, merged